#!/usr/bin/env bash

# Install Nginx if not already installed
sudo apt update
sudo apt install -y nginx

# Create a new Nginx configuration file for the redirection
sudo tee /etc/nginx/sites-available/redirect << EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    # Remove default Nginx configuration
    location / {
        return 404;
    }
}
EOF

# Enable the new Nginx configuration by creating a symbolic link
sudo ln -s /etc/nginx/sites-available/redirect /etc/nginx/sites-enabled/

# Test Nginx configuration
sudo nginx -t

# Restart Nginx to apply the changes
sudo service nginx restart
