#!/usr/bin/env bash
# run nginx s nginx user
# nginx must be listening on all active IPS on port 8080
# you cannot use apt-get remove
# this script configures the container to fit the above requirements

file='/etc/nginx/sites-available/default'

# kill apache2 server
pkill -f apache2

sed -i 's/user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/listen 80;/listen 8080;/g' /etc/nginx/sites-available/default

# Restart Nginx service
service nginx restart
